server:
  port: 3333
spring:
  application:
    name: STOCK_APP_ZUEAL_PROXY 
    
zuul: 
 prefix: /ms   
 routes:
   greet:
      path: /stockPriceApi/**
      serviceId: STOCK-PRICE-API
   welcome:
      path: /stockCalcApi/**
      serviceId: STOCK-CALC-API

